const Movies = require("./models/movies.model");

let moviesArray = [
  {
    adult: false,
    backdrop_path: "/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg",
    genre_ids: [10751, 35, 12, 14],
    id: 950387,
    original_language: "en",
    original_title: "A Minecraft Movie",
    overview:
      "Four misfits find themselves struggling with ordinary problems when they are suddenly pulled through a mysterious portal into the Overworld: a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master this world while embarking on a magical quest with an unexpected, expert crafter, Steve.",
    popularity: 990.9442,
    poster_path: "/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg",
    release_date: "2025-03-31",
    title: "A Minecraft Movie",
    video: false,
    vote_average: 6.114,
    vote_count: 348,
  },
  {
    adult: false,
    backdrop_path: "/is9bmV6uYXu7LjZGJczxrjJDlv8.jpg",
    genre_ids: [28, 12],
    id: 1229730,
    original_language: "fr",
    original_title: "Carjackers",
    overview:
      "By day, they're invisible—valets, hostesses, and bartenders at a luxury hotel. By night, they're the Carjackers, a crew of skilled drivers who track and rob wealthy clients on the road. As they plan their ultimate heist, the hotel director hires a ruthless hitman, to stop them at all costs. With danger closing in, can Nora, Zoe, Steve, and Prestance pull off their biggest score yet?",
    popularity: 297.0009,
    poster_path: "/wbkPMTz2vVai7Ujyp0ag7AM9SrO.jpg",
    release_date: "2025-03-27",
    title: "Carjackers",
    video: false,
    vote_average: 6.179,
    vote_count: 95,
  },
  {
    adult: false,
    backdrop_path: "/ce3prrjh9ZehEl5JinNqr4jIeaB.jpg",
    genre_ids: [28, 53, 878],
    id: 822119,
    original_language: "en",
    original_title: "Captain America: Brave New World",
    overview:
      "After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.",
    popularity: 283.1613,
    poster_path: "/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
    release_date: "2025-02-12",
    title: "Captain America: Brave New World",
    video: false,
    vote_average: 6.099,
    vote_count: 1248,
  },
  {
    adult: false,
    backdrop_path: "/gsQJOfeW45KLiQeEIsom94QPQwb.jpg",
    genre_ids: [28, 53],
    id: 1125899,
    original_language: "en",
    original_title: "Cleaner",
    overview:
      "When a group of radical activists take over an energy company's annual gala, seizing 300 hostages, an ex-soldier turned window cleaner suspended 50 storeys up on the outside of the building must save those trapped inside, including her younger brother.",
    popularity: 263.1996,
    poster_path: "/mwzDApMZAGeYCEVjhegKvCzDX0W.jpg",
    release_date: "2025-02-19",
    title: "Cleaner",
    video: false,
    vote_average: 6.503,
    vote_count: 179,
  },
  {
    adult: false,
    backdrop_path: "/llXzJt0Rno7OsaXJe8ecQsNRVBo.jpg",
    genre_ids: [14, 12, 28],
    id: 324544,
    original_language: "en",
    original_title: "In the Lost Land",
    overview:
      "A queen sends the powerful and feared sorceress Gray Alys to the ghostly wilderness of the Lost Lands in search of a magical power, where the sorceress and her guide, the drifter Boyce must outwit and outfight man and demon.",
    popularity: 534.2664,
    poster_path: "/dDlfjR7gllmr8HTeN6rfrYhTdwX.jpg",
    release_date: "2025-02-27",
    title: "In the Lost Land",
    video: false,
    vote_average: 6.1,
    vote_count: 47,
  },
  {
    adult: false,
    backdrop_path: "/xBrx6O1RIhjtWmVthZIANuQz7Z2.jpg",
    genre_ids: [28, 80, 53],
    id: 1197306,
    original_language: "en",
    original_title: "A Working Man",
    overview:
      "Levon Cade left behind a decorated military career in the black ops to live a simple life working construction. But when his boss's daughter, who is like family to him, is taken by human traffickers, his search to bring her home uncovers a world of corruption far greater than he ever could have imagined.",
    popularity: 215.8897,
    poster_path: "/6FRFIogh3zFnVWn7Z6zcYnIbRcX.jpg",
    release_date: "2025-03-26",
    title: "A Working Man",
    video: false,
    vote_average: 6.402,
    vote_count: 169,
  },
  {
    adult: false,
    backdrop_path: "/hGLywNhy1Fo1rNFHsNZsXGS69B8.jpg",
    genre_ids: [878, 35, 12],
    id: 696506,
    original_language: "en",
    original_title: "Mickey 17",
    overview:
      "Unlikely hero Mickey Barnes finds himself in the extraordinary circumstance of working for an employer who demands the ultimate commitment to the job… to die, for a living.",
    popularity: 241.9858,
    poster_path: "/edKpE9B5qN3e559OuMCLZdW1iBZ.jpg",
    release_date: "2025-02-28",
    title: "Mickey 17",
    video: false,
    vote_average: 6.953,
    vote_count: 1323,
  },
  {
    adult: false,
    backdrop_path: "/AlpDRp3Qaf2JvlQDzXS8kiYxTf8.jpg",
    genre_ids: [28, 53],
    id: 1212855,
    original_language: "en",
    original_title: "Fight or Flight",
    overview:
      "A mercenary takes on the job of tracking down a target on a plane but must protect her when they're surrounded by people trying to kill both of them.",
    popularity: 197.3977,
    poster_path: "/x4nWnfgJvL045rcUCSJzfgIIY9i.jpg",
    release_date: "2025-04-03",
    title: "Fight or Flight",
    video: false,
    vote_average: 4.63,
    vote_count: 27,
  },
  {
    adult: false,
    backdrop_path: "/ibF5XVxTzf1ayzZrmiJqgeQ39Qk.jpg",
    genre_ids: [28, 10752],
    id: 1373723,
    original_language: "en",
    original_title: "The Codes of War",
    overview:
      "War stories about family, ethics and honor include the true story of two U.S. Marines who in a span of six seconds, must stand their ground to stop a suicide truck bomb, a Navy Corpsman who attempts to hold on to his humanity, and a WW2 soldier who gets separated from his squad and is forced to re-evaluate his code.",
    popularity: 191.6448,
    poster_path: "/oXeiQAfRK90pxxhP5iKPXQqAIN1.jpg",
    release_date: "2025-03-20",
    title: "The Codes of War",
    video: false,
    vote_average: 6.102,
    vote_count: 44,
  },
  {
    adult: false,
    backdrop_path: "/9OO6I25MHhCDd0XwNk4oZl0fpwB.jpg",
    genre_ids: [28, 18],
    id: 1261050,
    original_language: "da",
    original_title: "De lydløse",
    overview:
      "In 2008, a group of men from Denmark and across Europe pull off the biggest heist of all time on Danish soil. Kasper, a boxer with few chances left in life, is offered the opportunity to plan the robbery by its foreign initiators.",
    popularity: 174.6724,
    poster_path: "/7NLY1jNwtZX1yVzwVoBeAhaBE8i.jpg",
    release_date: "2024-10-31",
    title: "The Quiet Ones",
    video: false,
    vote_average: 4.983,
    vote_count: 30,
  },
  {
    adult: false,
    backdrop_path: "/nhx0ttmAS2w8e6hyIcKoNvgHoix.jpg",
    genre_ids: [27, 53, 14],
    id: 1020414,
    original_language: "en",
    original_title: "Peter Pan's Neverland Nightmare",
    overview:
      "Wendy Darling strikes out in an attempt to rescue her brother Michael from the clutches of the evil Peter Pan who intends to send him to Neverland. Along the way she meets a twisted Tinkerbell, who is hooked on what she thinks is fairy dust.",
    popularity: 156.8976,
    poster_path: "/mOR1Ks0EcXocwMV4EPv4letz0F5.jpg",
    release_date: "2025-01-13",
    title: "Peter Pan's Neverland Nightmare",
    video: false,
    vote_average: 5.104,
    vote_count: 48,
  },
  {
    adult: false,
    backdrop_path: "/9ctmJLf3uUngYkwHbRttukm2n5l.jpg",
    genre_ids: [18, 9648, 53],
    id: 1233575,
    original_language: "en",
    original_title: "Black Bag",
    overview:
      "When intelligence agent Kathryn Woodhouse is suspected of betraying the nation, her husband – also a legendary agent – faces the ultimate test of whether to be loyal to his marriage, or his country.",
    popularity: 117.2334,
    poster_path: "/hHPovtU4b96LHcoeEwRkGHI5btw.jpg",
    release_date: "2025-03-12",
    title: "Black Bag",
    video: false,
    vote_average: 6.379,
    vote_count: 301,
  },
  {
    adult: false,
    backdrop_path: "/jiKwojRdwMYsDEMxQp5NFS3sOKb.jpg",
    genre_ids: [27],
    id: 1282980,
    original_language: "en",
    original_title: "825 Forest Road",
    overview:
      "After a family tragedy, Chuck Wilson hopes to start a new life in Ashland Falls with his wife Maria and little sister Elizabeth, but he quickly discovers that the town has a dark history of being haunted by a ghostly woman who drives residents to suicide.",
    popularity: 142.9193,
    poster_path: "/ohESp5Nw49OD4ExCeNYCEIGX2iq.jpg",
    release_date: "2025-04-04",
    title: "825 Forest Road",
    video: false,
    vote_average: 5.722,
    vote_count: 18,
  },
  {
    adult: false,
    backdrop_path: "/e807jDKiFcntZS32ze88X6I96OD.jpg",
    genre_ids: [16, 28],
    id: 1297763,
    original_language: "ja",
    original_title: "ニンジャバットマン対ヤクザリーグ",
    overview:
      "The Batman family has returned to the present to discover that Japan has disappeared, and a giant island - Hinomoto - is now in the sky over Gotham City.  At the top sit the Yakuza, a group of superpowered individuals who reign without honor or humanity and look suspiciously like the Justice League. Now, it’s up to Batman and his allies to save Gotham!",
    popularity: 120.0763,
    poster_path: "/sVVT6GYFErVv0Lcc9NvqCu0iOxO.jpg",
    release_date: "2025-03-17",
    title: "Batman Ninja vs. Yakuza League",
    video: false,
    vote_average: 6.627,
    vote_count: 122,
  },
  {
    adult: false,
    backdrop_path: "/xkjWiRQtrenqGRWO2Enry2JIl4d.jpg",
    genre_ids: [27],
    id: 1388366,
    original_language: "pt",
    original_title: "Popeye the Slayer Man",
    overview:
      'A curious group of friends sneak into an abandoned spinach canning factory to film a documentary on the legend of the "Sailor Man," who is said to haunt the factory and local docks.',
    popularity: 106.8782,
    poster_path: "/nVwu3mN7hr1yF467pGct3yQFM41.jpg",
    release_date: "2025-03-21",
    title: "Popeye the Slayer Man",
    video: false,
    vote_average: 6.086,
    vote_count: 70,
  },
  {
    adult: false,
    backdrop_path: "/hwlyY7LJdEFbCPaGNXiskKKmJ5X.jpg",
    genre_ids: [28, 80, 53],
    id: 1126166,
    original_language: "en",
    original_title: "Flight Risk",
    overview:
      "A U.S. Marshal escorts a government witness to trial after he's accused of getting involved with a mob boss, only to discover that the pilot who is transporting them is also a hitman sent to assassinate the informant. After they subdue him, they're forced to fly together after discovering that there are others attempting to eliminate them.",
    popularity: 112.0742,
    poster_path: "/q0bCG4NX32iIEsRFZqRtuvzNCyZ.jpg",
    release_date: "2025-01-22",
    title: "Flight Risk",
    video: false,
    vote_average: 6.104,
    vote_count: 603,
  },
  {
    adult: false,
    backdrop_path: "/xb9wpY31SeVZbfkevYuolhfV63w.jpg",
    genre_ids: [10751, 14],
    id: 447273,
    original_language: "en",
    original_title: "Snow White",
    overview:
      "Princess Snow White flees the castle when the Evil Queen, in her jealousy over Snow White's inner beauty, tries to kill her. Deep into the dark woods, she stumbles upon seven magical dwarves and a young thief named Jonathan. Together, they strive to survive the Queen's relentless pursuit and aspire to take back the kingdom in the process.",
    popularity: 105.1103,
    poster_path: "/xWWg47tTfparvjK0WJNX4xL8lW2.jpg",
    release_date: "2025-03-19",
    title: "Snow White",
    video: false,
    vote_average: 4.549,
    vote_count: 525,
  },
  {
    adult: false,
    backdrop_path: "/sulUXRukzh7WSK34y8mnaUcHo3y.jpg",
    genre_ids: [10749, 35, 18],
    id: 1254786,
    original_language: "en",
    original_title: "The Life List",
    overview:
      "When her mother sends her on a quest to complete a teenage bucket list, a young woman uncovers family secrets, finds romance — and rediscovers herself.",
    popularity: 103.3923,
    poster_path: "/5fg98cVo7da7OIK45csdLSd4NaU.jpg",
    release_date: "2025-03-27",
    title: "The Life List",
    video: false,
    vote_average: 6.882,
    vote_count: 211,
  },
  {
    adult: false,
    backdrop_path: "/3kzw6Rw7TBujqtchJS2TSP3O2US.jpg",
    genre_ids: [27, 9648, 53],
    id: 1202479,
    original_language: "en",
    original_title: "Opus",
    overview:
      "A young writer is invited to the remote compound of a legendary pop star who mysteriously disappeared thirty years ago. Surrounded by the star's cult of sycophants and intoxicated journalists, she finds herself in the middle of his twisted plan.",
    popularity: 70.4611,
    poster_path: "/m0du9dsiOVeb0SgfqR8ZAEPRxww.jpg",
    release_date: "2025-03-13",
    title: "Opus",
    video: false,
    vote_average: 5.325,
    vote_count: 57,
  },
  {
    adult: false,
    backdrop_path: "/lsgT602GYV8ts97sKH1gWFtQs1k.jpg",
    genre_ids: [16, 12, 35, 10751, 14],
    id: 1104845,
    original_language: "en",
    original_title: "Plankton: The Movie",
    overview:
      "Plankton's tangled love story with his sentient computer wife goes sideways when she takes a stand — and decides to destroy the world without him.",
    popularity: 76.9145,
    poster_path: "/hGaUNLF5VZbg9ovPTyjm9Rv5xWz.jpg",
    release_date: "2025-03-08",
    title: "Plankton: The Movie",
    video: false,
    vote_average: 6.953,
    vote_count: 75,
  },

  {
    adult: false,
    backdrop_path: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
    genre_ids: [18, 80],
    id: 278,
    original_language: "en",
    original_title: "The Shawshank Redemption",
    overview:
      "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    popularity: 38.8609,
    poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    release_date: "1994-09-23",
    title: "The Shawshank Redemption",
    video: false,
    vote_average: 8.7,
    vote_count: 28092,
  },
  {
    adult: false,
    backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    genre_ids: [18, 80],
    id: 238,
    original_language: "en",
    original_title: "The Godfather",
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    popularity: 40.7744,
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    release_date: "1972-03-14",
    title: "The Godfather",
    video: false,
    vote_average: 8.686,
    vote_count: 21298,
  },
  {
    adult: false,
    backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
    genre_ids: [18, 80],
    id: 240,
    original_language: "en",
    original_title: "The Godfather Part II",
    overview:
      "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    popularity: 19.2773,
    poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    release_date: "1974-12-20",
    title: "The Godfather Part II",
    video: false,
    vote_average: 8.569,
    vote_count: 12872,
  },
  {
    adult: false,
    backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
    genre_ids: [18, 36, 10752],
    id: 424,
    original_language: "en",
    original_title: "Schindler's List",
    overview:
      "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    popularity: 19.8207,
    poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    release_date: "1993-12-15",
    title: "Schindler's List",
    video: false,
    vote_average: 8.563,
    vote_count: 16340,
  },
  {
    adult: false,
    backdrop_path: "/bxgTSUenZDHNFerQ1whRKplrMKF.jpg",
    genre_ids: [18],
    id: 389,
    original_language: "en",
    original_title: "12 Angry Men",
    overview:
      "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
    popularity: 12.5604,
    poster_path: "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
    release_date: "1957-04-10",
    title: "12 Angry Men",
    video: false,
    vote_average: 8.5,
    vote_count: 9052,
  },
  {
    adult: false,
    backdrop_path: "/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg",
    genre_ids: [16, 10751, 14],
    id: 129,
    original_language: "ja",
    original_title: "千と千尋の神隠し",
    overview:
      "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    popularity: 32.3974,
    poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    release_date: "2001-07-20",
    title: "Spirited Away",
    video: false,
    vote_average: 8.537,
    vote_count: 17007,
  },
  {
    adult: false,
    backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
    genre_ids: [35, 18, 10749],
    id: 19404,
    original_language: "hi",
    original_title: "दिलवाले दुल्हनिया ले जायेंगे",
    overview:
      "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
    popularity: 6.0194,
    poster_path: "/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg",
    release_date: "1995-10-20",
    title: "Dilwale Dulhania Le Jayenge",
    video: false,
    vote_average: 8.518,
    vote_count: 4479,
  },
  {
    adult: false,
    backdrop_path: "/oOv2oUXcAaNXakRqUPxYq5lJURz.jpg",
    genre_ids: [18, 28, 80, 53],
    id: 155,
    original_language: "en",
    original_title: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    popularity: 31.541,
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-16",
    title: "The Dark Knight",
    video: false,
    vote_average: 8.519,
    vote_count: 33679,
  },
  {
    adult: false,
    backdrop_path: "/vxJ08SvwomfKbpboCWynC3uqUg4.jpg",
    genre_ids: [14, 18, 80],
    id: 497,
    original_language: "en",
    original_title: "The Green Mile",
    overview:
      "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
    popularity: 18.7095,
    poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
    release_date: "1999-12-10",
    title: "The Green Mile",
    video: false,
    vote_average: 8.504,
    vote_count: 17988,
  },
  {
    adult: false,
    backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    genre_ids: [35, 53, 18],
    id: 496243,
    original_language: "ko",
    original_title: "기생충",
    overview:
      "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    popularity: 25.799,
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    release_date: "2019-05-30",
    title: "Parasite",
    video: false,
    vote_average: 8.5,
    vote_count: 18904,
  },
  {
    adult: false,
    backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    genre_ids: [53, 80],
    id: 680,
    original_language: "en",
    original_title: "Pulp Fiction",
    overview:
      "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    popularity: 22.3255,
    poster_path: "/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
    release_date: "1994-09-10",
    title: "Pulp Fiction",
    video: false,
    vote_average: 8.49,
    vote_count: 28535,
  },
  {
    adult: false,
    backdrop_path: "/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg",
    genre_ids: [16, 10749, 18],
    id: 372058,
    original_language: "ja",
    original_title: "君の名は。",
    overview:
      "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    popularity: 22.2043,
    poster_path: "/8GJsy7w7frGquw1cy9jasOGNNI1.jpg",
    release_date: "2016-08-26",
    title: "Your Name.",
    video: false,
    vote_average: 8.485,
    vote_count: 11703,
  },
  {
    adult: false,
    backdrop_path: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
    genre_ids: [12, 14, 28],
    id: 122,
    original_language: "en",
    original_title: "The Lord of the Rings: The Return of the King",
    overview:
      "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​",
    popularity: 24.5269,
    poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    release_date: "2003-12-17",
    title: "The Lord of the Rings: The Return of the King",
    video: false,
    vote_average: 8.482,
    vote_count: 24936,
  },
  {
    adult: false,
    backdrop_path: "/ghgfzbEV7kbpbi1O8eIILKVXEA8.jpg",
    genre_ids: [35, 18, 10749],
    id: 13,
    original_language: "en",
    original_title: "Forrest Gump",
    overview:
      "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
    popularity: 20.6572,
    poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    release_date: "1994-06-23",
    title: "Forrest Gump",
    video: false,
    vote_average: 8.467,
    vote_count: 28067,
  },
  {
    adult: false,
    backdrop_path: "/x4biAVdPVCghBlsVIzB6NmbghIz.jpg",
    genre_ids: [37],
    id: 429,
    original_language: "it",
    original_title: "Il buono, il brutto, il cattivo",
    overview:
      "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
    popularity: 18.6017,
    poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
    release_date: "1966-12-22",
    title: "The Good, the Bad and the Ugly",
    video: false,
    vote_average: 8.462,
    vote_count: 8918,
  },
  {
    adult: false,
    backdrop_path: "/7TF4p86ZafnxFuNqWdhpHXFO244.jpg",
    genre_ids: [18, 80],
    id: 769,
    original_language: "en",
    original_title: "GoodFellas",
    overview:
      "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
    popularity: 16.1189,
    poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    release_date: "1990-09-12",
    title: "GoodFellas",
    video: false,
    vote_average: 8.456,
    vote_count: 13263,
  },
  {
    adult: false,
    backdrop_path: "/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg",
    genre_ids: [28, 18],
    id: 346,
    original_language: "ja",
    original_title: "七人の侍",
    overview:
      "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
    popularity: 5.7426,
    poster_path: "/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
    release_date: "1954-04-26",
    title: "Seven Samurai",
    video: false,
    vote_average: 8.455,
    vote_count: 3853,
  },
  {
    adult: false,
    backdrop_path: "/8sNiAPPYU14PUepFNeSNGUTiHW.jpg",
    genre_ids: [12, 18, 878],
    id: 157336,
    original_language: "en",
    original_title: "Interstellar",
    overview:
      "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    popularity: 44.7344,
    poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    release_date: "2014-11-05",
    title: "Interstellar",
    video: false,
    vote_average: 8.5,
    vote_count: 36890,
  },
  {
    adult: false,
    backdrop_path: "/tDFvXn4tane9lUvFAFAUkMylwSr.jpg",
    genre_ids: [16, 18, 10752],
    id: 12477,
    original_language: "ja",
    original_title: "火垂るの墓",
    overview:
      "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
    popularity: 0.0134,
    poster_path: "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
    release_date: "1988-04-16",
    title: "Grave of the Fireflies",
    video: false,
    vote_average: 8.451,
    vote_count: 5831,
  },
  {
    adult: false,
    backdrop_path: "/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg",
    genre_ids: [35, 18],
    id: 637,
    original_language: "it",
    original_title: "La vita è bella",
    overview:
      "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
    popularity: 9.0034,
    poster_path: "/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
    release_date: "1997-12-20",
    title: "Life Is Beautiful",
    video: false,
    vote_average: 8.448,
    vote_count: 13285,
  },
  {
    adult: false,
    backdrop_path: "/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg",
    genre_ids: [10751, 35, 12, 14],
    id: 950387,
    original_language: "en",
    original_title: "A Minecraft Movie 2",
    overview:
      "Four misfits find themselves struggling with ordinary problems when they are suddenly pulled through a mysterious portal into the Overworld: a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master this world while embarking on a magical quest with an unexpected, expert crafter, Steve.",
    popularity: 990.9442,
    poster_path: "/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg",
    release_date: "2025-03-31",
    title: "A Minecraft Movie 2",
    video: false,
    vote_average: 6.123,
    vote_count: 346,
  },
  {
    adult: false,
    backdrop_path: "/tYzhkVPWXsORLOCPXIBixboKIjS.jpg",
    genre_ids: [14, 12, 28],
    id: 324544,
    original_language: "en",
    original_title: "In the Lost Lands",
    overview:
      "A queen sends the powerful and feared sorceress Gray Alys to the ghostly wilderness of the Lost Lands in search of a magical power, where the sorceress and her guide, the drifter Boyce must outwit and outfight man and demon.",
    popularity: 534.2664,
    poster_path: "/dDlfjR7gllmr8HTeN6rfrYhTdwX.jpg",
    release_date: "2025-02-27",
    title: "In the Lost Lands",
    video: false,
    vote_average: 6.064,
    vote_count: 47,
  },
  {
    adult: false,
    backdrop_path: "/AlpDRp3Qaf2JvlQDzXS8kiYxTf8.jpg",
    genre_ids: [28, 53],
    id: 1212855,
    original_language: "en",
    original_title: "Flight",
    overview:
      "A mercenary takes on the job of tracking down a target on a plane but must protect her when they're surrounded by people trying to kill both of them.",
    popularity: 197.3977,
    poster_path: "/x4nWnfgJvL045rcUCSJzfgIIY9i.jpg",
    release_date: "2025-04-03",
    title: "Flight",
    video: false,
    vote_average: 4.63,
    vote_count: 27,
  },
  {
    adult: false,
    backdrop_path: "/nhx0ttmAS2w8e6hyIcKoNvgHoix.jpg",
    genre_ids: [27, 53, 14],
    id: 1020414,
    original_language: "en",
    original_title: "Peter Pan's Neverland Nightmare",
    overview:
      "Wendy Darling strikes out in an attempt to rescue her brother Michael from the clutches of the evil Peter Pan who intends to send him to Neverland. Along the way she meets a twisted Tinkerbell, who is hooked on what she thinks is fairy dust.",
    popularity: 156.8976,
    poster_path: "/mOR1Ks0EcXocwMV4EPv4letz0F5.jpg",
    release_date: "2025-01-13",
    title: "Peter Pan's Neverland Nightmare",
    video: false,
    vote_average: 5.104,
    vote_count: 48,
  },
  {
    adult: false,
    backdrop_path: "/9ctmJLf3uUngYkwHbRttukm2n5l.jpg",
    genre_ids: [18, 9648, 53],
    id: 1233575,
    original_language: "en",
    original_title: "Black Bag",
    overview:
      "When intelligence agent Kathryn Woodhouse is suspected of betraying the nation, her husband – also a legendary agent – faces the ultimate test of whether to be loyal to his marriage, or his country.",
    popularity: 117.2334,
    poster_path: "/hHPovtU4b96LHcoeEwRkGHI5btw.jpg",
    release_date: "2025-03-12",
    title: "Black Bag",
    video: false,
    vote_average: 6.379,
    vote_count: 301,
  },
  {
    adult: false,
    backdrop_path: "/xb9wpY31SeVZbfkevYuolhfV63w.jpg",
    genre_ids: [10751, 14],
    id: 447273,
    original_language: "en",
    original_title: "Snow White",
    overview:
      "Princess Snow White flees the castle when the Evil Queen, in her jealousy over Snow White's inner beauty, tries to kill her. Deep into the dark woods, she stumbles upon seven magical dwarves and a young thief named Jonathan. Together, they strive to survive the Queen's relentless pursuit and aspire to take back the kingdom in the process.",
    popularity: 105.1103,
    poster_path: "/xWWg47tTfparvjK0WJNX4xL8lW2.jpg",
    release_date: "2025-03-19",
    title: "Snow White",
    video: false,
    vote_average: 4.549,
    vote_count: 525,
  },
  {
    adult: false,
    backdrop_path: "/AtciHGgpOU7ngsVhXbS2S5Spdlv.jpg",
    genre_ids: [28, 35],
    id: 1077782,
    original_language: "en",
    original_title: "Old Guy",
    overview:
      "Stuck at a dead end but vying for the love of spunky club manager Anata, aging contract killer Danny Dolinski is thrilled when The Company pulls him back in the field, but only to train Gen Z newcomer Wihlborg, a prodigy assassin with an attitude.",
    popularity: 78.3558,
    poster_path: "/qx0NV9VEZTXN5c1qruhyHclMauY.jpg",
    release_date: "2024-12-13",
    title: "Old Guy",
    video: false,
    vote_average: 5.575,
    vote_count: 73,
  },
  {
    adult: false,
    backdrop_path: "/3kzw6Rw7TBujqtchJS2TSP3O2US.jpg",
    genre_ids: [27, 9648, 53],
    id: 1202479,
    original_language: "en",
    original_title: "Opus",
    overview:
      "A young writer is invited to the remote compound of a legendary pop star who mysteriously disappeared thirty years ago. Surrounded by the star's cult of sycophants and intoxicated journalists, she finds herself in the middle of his twisted plan.",
    popularity: 70.4611,
    poster_path: "/m0du9dsiOVeb0SgfqR8ZAEPRxww.jpg",
    release_date: "2025-03-13",
    title: "Opus",
    video: false,
    vote_average: 5.325,
    vote_count: 57,
  },
  {
    adult: false,
    backdrop_path: "/bA4Io3xv46oEyP4O51uU0EKbluF.jpg",
    genre_ids: [28, 80],
    id: 995926,
    original_language: "ko",
    original_title: "베테랑 2",
    overview:
      "The veteran detective Seo Do-cheol and his team at Major Crimes, relentless in their pursuit of criminals, join forces with rookie cop Park Sun-woo to track down a serial killer who has plunged the nation into turmoil.",
    popularity: 70.699,
    poster_path: "/gAtP0usArK5gVOBObnsENKLwML8.jpg",
    release_date: "2024-09-13",
    title: "I, the Executioner",
    video: false,
    vote_average: 6.9,
    vote_count: 50,
  },
  {
    adult: false,
    backdrop_path: "/jl2YIADk391yc6Qjy9JhgCRkHJk.jpg",
    genre_ids: [16, 18, 35],
    id: 1064486,
    original_language: "en",
    original_title: "Memoir of a Snail",
    overview:
      "Forcibly separated from her twin brother when they are orphaned, a melancholic misfit learns how to find confidence within herself amid the clutter of misfortunes and everyday life.",
    popularity: 69.816,
    poster_path: "/57AgZv1ITeBLShiNdchZ5153evs.jpg",
    release_date: "2024-10-17",
    title: "Memoir of a Snail",
    video: false,
    vote_average: 7.974,
    vote_count: 363,
  },
  {
    adult: false,
    backdrop_path: "/6dC7ULfiutxwEAs7LjWHL2Tc7Zv.jpg",
    genre_ids: [27, 35],
    id: 1124620,
    original_language: "en",
    original_title: "The Monkey",
    overview:
      "When twin brothers find a mysterious wind-up monkey, a series of outrageous deaths tear their family apart. Twenty-five years later, the monkey begins a new killing spree forcing the estranged brothers to confront the cursed toy.",
    popularity: 61.3016,
    poster_path: "/yYa8Onk9ow7ukcnfp2QWVvjWYel.jpg",
    release_date: "2025-02-14",
    title: "The Monkey",
    video: false,
    vote_average: 5.854,
    vote_count: 411,
  },
  {
    adult: false,
    backdrop_path: "/iXU87IdtNsYt7n6OigPJBDdbFf1.jpg",
    genre_ids: [10751, 35, 12, 16],
    id: 774370,
    original_language: "en",
    original_title: "Dog Man",
    overview:
      "When a faithful police dog and his human police officer owner are injured together on the job, a harebrained but life-saving surgery fuses the two of them together and Dog Man is born. Dog Man is sworn to protect and serve—and fetch, sit and roll over. As Dog Man embraces his new identity and strives to impress his Chief, he must stop the pretty evil plots of feline supervillain Petey the Cat.",
    popularity: 48.9989,
    poster_path: "/89wNiexZdvLQ41OQWIsQy4O6jAQ.jpg",
    release_date: "2025-01-24",
    title: "Dog Man",
    video: false,
    vote_average: 7.777,
    vote_count: 197,
  },
  {
    adult: false,
    backdrop_path: "/qSOMdbZ6AOdHR999HWwVAh6ALFI.jpg",
    genre_ids: [28, 80, 53],
    id: 1249289,
    original_language: "en",
    original_title: "Alarum",
    overview:
      "Two married spies caught in the crosshairs of an international intelligence network will stop at nothing to obtain a critical asset. Joe and Lara are agents living off the grid whose quiet retreat at a winter resort is blown to shreds when members of the old guard suspect the two may have joined an elite team of rogue spies, known as Alarum.",
    popularity: 42.3619,
    poster_path: "/v313aUGmMNj6yNveaiQXysBmjVS.jpg",
    release_date: "2025-01-16",
    title: "Alarum",
    video: false,
    vote_average: 5.816,
    vote_count: 244,
  },
  {
    adult: false,
    backdrop_path: "/ag66gJCiZ06q1GSJuQlhGLi3Udx.jpg",
    genre_ids: [27, 53],
    id: 1138194,
    original_language: "en",
    original_title: "Heretic",
    overview:
      "Two young missionaries are forced to prove their faith when they knock on the wrong door and are greeted by a diabolical Mr. Reed, becoming ensnared in his deadly game of cat-and-mouse.",
    popularity: 39.7692,
    poster_path: "/fr96XzlzsONrQrGfdLMiwtQjott.jpg",
    release_date: "2024-10-31",
    title: "Heretic",
    video: false,
    vote_average: 7.071,
    vote_count: 1507,
  },
  {
    adult: false,
    backdrop_path: "/hfTyu2VPBqLRPo2DauW8q7bh9bm.jpg",
    genre_ids: [10751, 35, 12],
    id: 516729,
    original_language: "en",
    original_title: "Paddington in Peru",
    overview:
      "Paddington travels to Peru to visit his beloved Aunt Lucy, who now resides at the Home for Retired Bears. With the Brown Family in tow, a thrilling adventure ensues when a mystery plunges them into an unexpected journey through the Amazon rainforest and up to the mountain peaks of Peru.",
    popularity: 33.5948,
    poster_path: "/1ffZAucqfvQu36x1C49XfOdjuOG.jpg",
    release_date: "2024-11-08",
    title: "Paddington in Peru",
    video: false,
    vote_average: 6.864,
    vote_count: 316,
  },
  {
    adult: false,
    backdrop_path: "/5saKQdU7JHNLmcLqVRmHGZ2Zj0E.jpg",
    genre_ids: [27, 53],
    id: 1355126,
    original_language: "id",
    original_title: "Pabrik Gula",
    overview:
      "A group of young men and women who work as seasonal workers in a sugar factory face terror from the kingdom of demons where the factory is located. They must find out the cause of the demons' anger, before the terror ends their lives.",
    popularity: 32.0625,
    poster_path: "/nwmR5EL5m8tcPBud6OwUyt8p5z1.jpg",
    release_date: "2025-03-31",
    title: "Pabrik Gula",
    video: false,
    vote_average: 6.2,
    vote_count: 5,
  },
  {
    adult: false,
    backdrop_path: "/dA3bM1H6aythAMCEfVJKPf5AyWb.jpg",
    genre_ids: [28, 12, 878],
    id: 986056,
    original_language: "en",
    original_title: "Thunderbolts*",
    overview:
      "After finding themselves ensnared in a death trap, seven disillusioned castoffs must embark on a dangerous mission that will force them to confront the darkest corners of their pasts.",
    popularity: 28.8216,
    poster_path: "/wHtjUUFmKSdXpiNNrprdTOioQKD.jpg",
    release_date: "2025-04-30",
    title: "Thunderbolts*",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/abSLxmkkXb3W2TXk8E9KbR7KQRj.jpg",
    genre_ids: [28, 27, 53],
    id: 970450,
    original_language: "en",
    original_title: "Werewolves",
    overview:
      "A year after a supermoon’s light activated a dormant gene, transforming humans into bloodthirsty werewolves and causing nearly a billion deaths, the nightmare resurfaces as the supermoon rises again. Two scientists attempt to stop the mutation but fail and must now struggle to reach one of their family homes.",
    popularity: 28.4672,
    poster_path: "/otXBlMPbFBRs6o2Xt6KX59Qw6dL.jpg",
    release_date: "2024-12-04",
    title: "Werewolves",
    video: false,
    vote_average: 6.195,
    vote_count: 346,
  },
  {
    adult: false,
    backdrop_path: "/aACb16EooaTSWGHwjsoeGe8DmyF.jpg",
    genre_ids: [10749, 18],
    id: 1109255,
    original_language: "it",
    original_title: "Parthenope",
    overview:
      "Parthenope, born in the sea near Naples in 1950, is beautiful, enigmatic, and intelligent. She is shamelessly courted by many. However, beauty comes at a cost.",
    popularity: 24.1637,
    poster_path: "/5SqICqUQaYFeZs1UnBZ4AN6DwcP.jpg",
    release_date: "2024-10-19",
    title: "Parthenope",
    video: false,
    vote_average: 6.867,
    vote_count: 497,
  },
  {
    adult: false,
    backdrop_path: "/8btfz81bOJ2lC7cujYBTw03wzg3.jpg",
    genre_ids: [16, 14, 12],
    id: 980477,
    original_language: "zh",
    original_title: "哪吒之魔童闹海",
    overview:
      "Following the Tribulation, although the souls of Ne Zha and Ao Bing were preserved, their physical bodies will soon be destroyed. Tai Yi Zhen Ren plans to use the Seven Colored Lotus to reshape their physical forms, but encounters numerous difficulties. What will become of Ne Zha and Ao Bing?",
    popularity: 22.6971,
    poster_path: "/kO9QAkh9sKVAPrmZVVoLF7oku3E.jpg",
    release_date: "2025-01-29",
    title: "Ne Zha 2",
    video: false,
    vote_average: 7.796,
    vote_count: 152,
  },
];
require("./db");
moviesArray = moviesArray.map((movie) => {
  movie.poster_path = "https://image.tmdb.org/t/p/w500" + movie.poster_path;
  return movie;
});
const playingNowMovies = moviesArray.slice(0, 20).map((movie) => {
  movie.playing_now = true;
  movie.top_rated = false;
  movie.upcoming = false;
  return movie;
});
console.log(moviesArray.length);

const topRatedMovies = moviesArray.slice(20, 40).map((movie) => {
  movie.top_rated = true;
  movie.playing_now = false;
  movie.upcoming = false;
  return movie;
});
const upcomingMovies = moviesArray.slice(40, 59).map((movie) => {
  movie.upcoming = true;
  movie.playing_now = false;
  movie.top_rated = false;
  return movie;
});

console.log("Playing Now Movies:", playingNowMovies.length);
console.log("Top Rated Movies:", topRatedMovies.length);
console.log("Upcoming Movies:", upcomingMovies);

console.log(topRatedMovies.length);
Movies.insertMany([...playingNowMovies, ...topRatedMovies, ...upcomingMovies])
  .then(() => {
    console.log("Data inserted successfully");
    mongoose.connection.close();
  })
  .catch((error) => {
    console.error("Error inserting data:", error);
  });
